- qucs/qucs/components/subcircuit.cpp
- qucs/qucs/qucs.cpp
- qucs/qucs/qucs.h
- qucs/qucs/qucs_actions.cpp
- qucs/qucs/qucs_init.cpp
- qucs/qucs/schematic.cpp
- qucs/qucs/schematic.h
- qucs/qucs/schematic_file.cpp
I am back haha, recently having work on my master thesis.
This PR and branch are gonna clean up qucs main program, there will be some further work on this branch. However, I think that too large PR will be more difficult to review and merge.
The PR now is refactoring project viewer at dock window with listview and QFileSystemModel. The model is always sync with file system state, so we don't need call "refresh" every time.
I also examine the code in qucs.cpp, and giving it some clean up.
> Project manager

- qucs/qucs/qucs.cpp
Fix directory not ended with "_prj" shows up at project viewer.
> fix not _prj show in project view

- qucs-core/src/CMakeLists.txt
Fix to #148 
* for generated files, delete file after testing
* for pre-written file, collect into a string replace loop
> fix Cmake test file

- qucs/qucs/qucs.cpp
- qucs/qucs/qucs.h
- qucs/qucs/qucs_actions.cpp
- qucs/qucs/qucs_init.cpp
Refactor open recent file function in qucsApp. Make theses function more clear.
actually mostly just copy and paste from "programming with qt4" handbook.
> Refactor update recent file function

- qucs/qucs/components/spicedialog.cpp
- qucs/qucs/qucs.cpp
- qucs/qucs/qucs.h
- qucs/qucs/qucs_actions.cpp
- qucs/qucs/qucs_init.cpp
This is a small (compare to work to do) clean up to qucs.cpp.
I removed some long comment out lines, do some deletion of unnecessary function.
> Clear qucs app

- qucs/qucs-activefilter/filter.cpp
- qucs/qucs-activefilter/filter.h
- qucs/qucs-activefilter/mfbfilter.cpp
This PR contains fix to avoid infinite loop at some active filter input parameters.
> Qucs-activefilter fix

- qucs/qucs/components/component.cpp
> Corrected netlist generation for disabled (shorted) components.

- qucs/configure.ac
- qucs/qucs/Makefile.am
- qucs/qucs/components/Makefile.am
- qucs/qucs/components/capacitor.cpp
- qucs/qucs/components/inductor.cpp
- qucs/qucs/extsimkernels/Makefile.am
@ra3xdh this should fix the build on Travis.
> Spice4qucs autotools

- qucs/qucs/CMakeLists.txt
- qucs/qucs/Makefile.am
- qucs/qucs/qucs.cpp
- qucs/qucs/qucs.h
- qucs/qucs/qucs_init.cpp
- qucs/qucs/schematicscene.cpp
- qucs/qucs/schematicscene.h
- qucs/qucs/schematicview.cpp
- qucs/qucs/schematicview.h
Add a basic skeleton of new schematic, various function will be added on this skeleton.
Recover open a new file function in qucs main, so we can open a schematic file and test how it work.
> Rewrite new schematicview

- qucs/qucs/dialogs/simmessage.cpp
- qucs/qucs/dialogs/simmessage.h
- qucs/qucs/main.cpp
- qucs/qucs/main.h
i'd like to play with a different qucsator implementation... 
(i can't think of a less intrusive patch that makes this work.)
also, this fixes a presumed bug in error reporting. SimProcess.Running did not work as potentially intended.
> QUCSATOR override

- qucs/qucs/dialogs/simmessage.cpp
this has undergone in merge 3ba25bfc570613
> (partially) redo b3a0b035 and d5f86539c

- qucs-core/Makefile.am
- qucs-core/src/components/verilog/Makefile.am
- qucs/contrib/innosetup/qucs.iss
- qucs/contrib/qucs-installer-win32.sh
- qucs/contrib/qucs-release.sh
- qucs/qucs/qucs_init.cpp
Preparing for a snapshot/release
> Snapshot 0.0.19

- qucs/qucs/schematic.cpp
- qucs/qucs/schematic.h
- qucs/qucs/schematic_element.cpp
* Make ElementCache Qt4 conform.
> Port Q3PtrList to QList for ElementCache

- qucs/qucs/mouseactions.cpp
- qucs/qucs/qucs.cpp
- qucs/qucs/schematic.cpp
i'm getting warnings that absolutely don't help. maybe this is work in progress by someone else. hopefully the fix works for the build bot...
> silence irrelevant compiler warnings

- qucs/qucs/diagrams/diagram.cpp
- qucs/qucs/diagrams/graph.cpp
- qucs/qucs/diagrams/graph.h
- qucs/qucs/diagrams/rect3ddiagram.cpp
- qucs/qucs/viewpainter.cpp
well, *some* details. the ScrPoints will hold more data in order to simplify diagrams. this PR increases flexibility a bit.
> hide ScrPoints implementation details

- qucs/qucs/diagrams/curvediagram.cpp
- qucs/qucs/diagrams/curvediagram.h
- qucs/qucs/diagrams/diagram.cpp
- qucs/qucs/diagrams/diagram.h
- qucs/qucs/diagrams/diagramdialog.cpp
- qucs/qucs/diagrams/graph.cpp
- qucs/qucs/diagrams/graph.h
- qucs/qucs/diagrams/marker.cpp
- qucs/qucs/diagrams/marker.h
- qucs/qucs/diagrams/markerdialog.cpp
- qucs/qucs/diagrams/polardiagram.cpp
- qucs/qucs/diagrams/polardiagram.h
- qucs/qucs/diagrams/psdiagram.cpp
- qucs/qucs/diagrams/psdiagram.h
- qucs/qucs/diagrams/rect3ddiagram.cpp
- qucs/qucs/diagrams/rect3ddiagram.h
- qucs/qucs/diagrams/rectdiagram.cpp
- qucs/qucs/diagrams/rectdiagram.h
- qucs/qucs/diagrams/smithdiagram.cpp
- qucs/qucs/diagrams/smithdiagram.h
- qucs/qucs/diagrams/tabdiagram.cpp
- qucs/qucs/diagrams/timingdiagram.cpp
- qucs/qucs/dialogs/sweepdialog.cpp
- qucs/qucs/mouseactions.cpp
- qucs/qucs/qucs.cpp
- qucs/qucs/qucs_actions.cpp
- qucs/qucs/viewpainter.cpp
this is actually only one commit on top of the other PR. maybe some motivation :)
(edit: rebased, new commit in said PR)
> use qt dashed lines implementation

- qucs/qucs/diagrams/marker.h
- qucs/qucs/mouseactions.cpp
- qucs/qucs/qucs.h
- qucs/qucs/qucs_actions.cpp
- qucs/qucs/schematic.h
- qucs/qucs/schematic_element.cpp
this PR fixes one particular weird case, the `const` Marker::pGraph. some additional code sanitation is required.
> fix a constness issue in Marker

- qucs/qucs/components/componentdialog.cpp
- qucs/qucs/imagewriter.cpp
- qucs/qucs/imagewriter.h
- qucs/qucs/schematic.cpp
- qucs/qucs/schematic.h
This PR is fix for both #319 and #320 .  Now Up/Down buttons work properly and Frame can be exported to image with Schematic. Please test on your side. Also dropped unused method `Schematic::getSchWidthAndHeight` .
> Fix for #319 and #320

- .appveyor.yml
- .travis.yml
- Avoid using SourceForge downloads for now. Using personal Dropbox which seems more reliable.
- Update Travis OSX instance to Qt version 4.8.7
> Ci workaround

- qucs/qucs/components/spicedialog.cpp
- qucs/qucs/components/spicefile.cpp
- qucs/qucs/components/subcircuit.cpp
- qucs/qucs/dialogs/importdialog.cpp
- qucs/qucs/dialogs/simmessage.cpp
- qucs/qucs/main.cpp
- qucs/qucs/main.h
- qucs/qucs/qucs.cpp
- qucs/qucs/qucs.h
- qucs/qucs/schematic.h
- qucs/qucs/schematic_file.cpp
> Crash subcircuit print netlist

- qucs-core/src/components/verilog/hicumL0V1p12.va
... bumped into this during some random testing.
> fix typo in hicumL2V2p22.va

- qucs/qucs/diagrams/marker.cpp
- qucs/qucs/diagrams/marker.h
- qucs/qucs/diagrams/markerdialog.cpp
the initialization was erroneously removed in bb7c9608c256. also rework
related comments.
> initialize Marker::Z0 to a default of 50.

- Makefile.am
- qucs-doc/configure.ac
- qucs-doc/technical/Makefile.am
- qucs-doc/tutorial/RFResModels/Makefile.am
- qucs-doc/tutorial/RFResModels/pics/Makefile.am
- qucs-doc/tutorial/activefilter/pics/Makefile.am
- qucs-doc/tutorial/textmode/pics/Makefile.am
* includes to distdir some pdf figures needed by qucs-doc. 
* do not copy qucs-test/.git/ directory into distdir.
> Fix docs build from tar

- qucs/qucs/components/vcresistor.cpp
This PR fixes typo in the description of the "Voltage Controlled Resistor" component.
> Fix of #405

- .travis.yml
- qucs-core/tests/Makefile.am
at home, i need this header to pass the tests.
i wonder, how the distcheck on travis passed...
> add qucs-core/tests/testDefine.h to EXTRA_DIST

- CMakeLists.txt
- qucs-core/CMakeLists.txt
- qucs-core/Makefile.am
- qucs-core/Makefile.env.in
- qucs-core/configure.ac
- qucs/CMakeLists.txt
- qucs/qucs/CMakeLists.txt
> Check for admsxml

- .appveyor.yml
- qucs-core/configure.ac
- qucs-core/src/Makefile.am
let's try the fix for gperf-3.04 and a guess for the Qt link error...
> Window build fixes

- qucs-core/src/converter/check_spice.cpp
> In3otd issue 487

- NEWS.md
> Fix typos on NEWS.md

- qucs-core/bootstrap
- qucs-core/configure.ac
Blacklist automake-1.10, like -1.11.
It was PR #515, now rebased to release-0.0.19
> Autoblacklist

- .appveyor.yml
just testing - trying to use Appveyor to build 32 and 64 bit binary packages
> [WIP] Use Appveyor to build 32 and 64 bit packages

- qucs/qucs/components/componentdialog.cpp
- qucs/qucs/dialogs/qucssettingsdialog.cpp
- qucs/qucs/main.cpp
- qucs/qucs/main.h
- qucs/qucs/octave_window.cpp
turn error message into something useful. this includes the review for 3c605ce (#525).
> Octave fix

- qucs/qucs/mouseactions.cpp
1. cross was painted wrong at scroll/zoom, fixed.
2. wire was painted wrong if corner changed(right button press while
wire creating).
> fixed 2 bugs in wire editing

- README.md
> Readme: Add info about branching strategy

- examples/Makefile.am
- qucs/qucs/main.cpp
maybe #538 needs yet another fix.
> install examples to examplesdir=${pkgdatadir}/examples

- qucs/qucs/octave_window.cpp
...quite embarrassing; after previously trying with #529 this should be the Right fix but please check :grin: .
> Fix 617 (crash with Octave dock)

- qucs/qucs/qucs.cpp
Quick fix for #629 ; seems ok here, but tested only briefly .
> 629 fix - paintings selection in symbol painting mode

- qucs/qucs/diagrams/rect3ddiagram.cpp
Modify rect3ddiagram.cpp to bring the hidden lines back.
Test cases are in qucs-test\testsuite\GUI_rect3ddiagram_prj.
> fix #386, hidden lines on 3D diagram

- qucs/qucs/dialogs/savedialog.cpp
- qucs/qucs/mouseactions.cpp
a couple of small fixes,
one for #683,
the other for the warning mentioned (with solution, thanks!) by andres [here](https://github.com/Qucs/qucs/commit/2e9f7d1373be75542373764397430bef411e6f9c#commitcomment-21969297)
> Small gui stuff

- qucs/qucs/qucs_init.cpp
This line was added back during conflict resolution for PR #669.
> Remove deprecated insertSeparator (again)

- qucs/PLATFORMS
reported by Eelco & Stella <post@boszicht213.nl>
> add armv7l-unknown-linux-gnueabihf to tested platforms

- qucs/qucs-transcalc/stripline.cpp
- qucs/qucs-transcalc/stripline.h
- qucs/qucs-transcalc/transline.h
This commit fixes some issues detected during the test of PR#510:
* The synthesis procedure is refined using the analysis formulae
* Removed redefinition of C0
> Fix for stripline code

- .appveyor.yml
- .travis.yml
- qucs/Makefile.am
- qucs/bootstrap
- qucs/configure.ac
- qucs/qucs/Makefile.am
- qucs/qucs/attach.cpp
- qucs/qucs/doesnotexist.sh
- qucs/qucs/helloworld.cpp
- qucs/qucs/helloworld.sh
- qucs/qucs/main.cpp
- qucs/qucs/main.h
- qucs/qucs/platform.h
to be merged as soon as CI is happy. expect portability related readjustments....
> basic dynamic loading

- qucs/qucs/CMakeLists.txt
- add files to the project
- add DL libraries at link time
> Add to CMake files used for dynamic load

- .travis.yml
Just because Travis warns that it will switch to Ubuntu Trusty (14.04 LTS) soon, wanted to check that everything still build fine there
Edit: added caching and a `cmake` build while I was at it
> Ubuntu Trusty environment on Travis

- qucs-core/src/spline.cpp
- qucs-core/src/spline.h
- qucs-core/tests/Makefile.am
- qucs-core/tests/Spline.cpp
This should fix the crash.
I will come back another day to refactor and use std:vector only.
> 676 pointer crash

- qucs/qucs/components/spicefile.cpp
- qucs/qucs/dialogs/simmessage.cpp
- qucs/qucs/qucs.cpp
- qucs/qucs/qucs_actions.cpp
- qucs/qucs/schematic_file.cpp
PATH is en environment variable, lets not mess with it. fixes #663
> fix PATH use

- Makefile.am
- configure.ac
> python override at toplevel

- qucs/configure.ac
- ./configure CXXFLAGS=-g now works as expected.
- simplify wording.
> cleanup, bugfix debug switch

- qucs/qucs/Makefile.am
- qucs/qucs/platform.h
- backport from component cleanup (untested)
- one more library
- switch to shared private libraries
- use libtool
> rearrange libraries

- .travis.yml
- qucs-core/src/converter/CMakeLists.txt
> Fix Travis exit code in if statements

- README.md
> Update dependencies on Readme. [skip ci]

- qucs/configure.ac
(use "make dist" to create a release tarball)
> cleanup stale "release" snippets in configure.ac

- qucs/README
- qucs/configure.ac
this is going to fix #768.
... and necessary for the Qt4/5 rework
> Qt selection wip

- qucs/tests/Makefile.am
- qucs/tests/netlist.sh
netlisting seems to break along the way. just catch as soon as possible
> netlist test

- qucs/configure.ac
- qucs/qucs/Makefile.am
- qucs/qucs/tests/ComponentTests.h
- qucs/qucs/tests/ElementTests.cpp
- qucs/qucs/tests/ElementTests.h
- qucs/qucs/tests/Makefile.am
- qucs/qucs/tests/SchematicTests.cpp
- qucs/qucs/tests/SchematicTests.h
- qucs/tests/Makefile.am
trying to make qucs/tests work with autotools
> fold in tests from cmake

- NEWS.md
> Draft Release Notes 0.0.20

- qucs/README
- qucs/configure.ac
- Romano Giannetti found a whitespace issue and proposed a fix.
- list pkg-config as a dependency.
> configure in qucs

- qucs/Makefile.am
- qucs/README
- qucs/configure.ac
- qucs/qucs/components/opt_sim.cpp
- qucs/qucs/dialogs/simmessage.cpp
- qucs/tests/Makefile.am
These fixes should be on release-0.0.20 first.
> Devel cherrypick

- qucs/qucs/components/component.cpp
- qucs/qucs/components/component.h
- qucs/qucs/components/ground.cpp
- qucs/qucs/schematic.h
- qucs/qucs/schematic_element.cpp
> element (de)selection

- qucs/qucs/qt_compat.h
- qucs/qucs/schematic_element.cpp
> drop elements dragged from menu

- qucs/qucs/components/component.cpp
- qucs/qucs/components/component.h
- qucs/qucs/components/ground.cpp
implement behaviour in Component, not in parser.
this fixes the GND issue found in #757
> workaround showName

- .travis.yml
- qucs/qucs/qucs.cpp
This PR is a cherry pick of ecae7fa and d30dc6d targeted to develop.
As @in3otd said [here](https://github.com/Qucs/qucs/pull/873#issuecomment-425209290), these commits need to be merge into develop. Then, we need to rebase and merge #871. Otherwise develop and release-0.0.20 will remain broken.
> Cherry pick 870 to develop

- .travis.yml
Use newer addon feature to handle homebrew packages.
> ci:osx: cleanup package dependencies.

- qucs/qucs-filter/ccoupled_shunt_resonators.cpp
- qucs/qucs-filter/cline_filter.cpp
- qucs/qucs-filter/filter.cpp
- qucs/qucs-filter/filter.h
- qucs/qucs-filter/lc_filter.cpp
- qucs/qucs-filter/line_filter.cpp
- qucs/qucs-filter/quarterwave_filter.cpp
- qucs/qucs-filter/qucsfilter.cpp
- qucs/qucs-filter/qucsfilter.h
- qucs/qucs-filter/qw_coupled_ring_filter.cpp
- qucs/qucs-filter/stepz_filter.cpp
See https://github.com/Qucs/qucs/issues/892
> Fix issue #892

- qucs/qucs/dialogs/vasettingsdialog.cpp
> fix duplicated include
